##
# This configuration is used for the live demo.
# - Site: https://aamod-demo.recoverysource.net/
# - Used: https://github.com/recoverysource/hugo-website/blob/master/.github/workflows/deploy.yml
##
baseURL: https://aamod-demo.recoverysource.net/
title: Statestown AA (Demonstration Webite)

languageCode: en-us
theme: [aamod, mainroad]
sectionPagesMenu: main
paginate: 100
buildFuture: true

Params:
  description: Basic demonstrations of the features provided by AAmod+Hugo with basic demonstration for usage.
  #REAL-source: https://github.com/recoverysource/aamod/tree/master/exampleSite
  source: https://github.com/recoverysource/hugo-website/tree/master
  #mapapikey: <https://developers.google.com/maps/documentation/embed/get-api-key>
  mapapikey: "AIzaSyA0zujVEN5nzVoZDI7G-Lo3GTwoLBckZGw"
  copyright: Statestown Demonstration
  phone: 123-456-7890
  logo:
    image: img/AAlogo.webp
    title: Statestown Demonstration
    subtitle: Local AA Meetings
  toc: true
  mainSections: [home, meetings, about, events]
  sidebar:
    single: right
    home: right
    widgets: [resources, eventsidemenu, aasites]
  widgets:

    resources:
      cached: true
      links:
      - title: Meeting Schedule
        url: /meeting-schedule.pdf
      - title: The Big Book
        url: https://www.aa.org/the-big-book

    aasites:
      cached: true
      links:
      - title: Recovery Source
        url: https://recoverysource.net/
      - title: A.A. World Services
        url: https://www.aa.org/
      - title: A.A. Grapevine
        url: http://www.aagrapevine.org/

markup:
  highlight:
    style: onesenterprise
  goldmark:
    renderer:
      # Permit raw HTML in content
      unsafe: true
